#pragma once

/**
 * Name: BLUEPROTOCOL-Win64-Shipping
 * Version: 1.6.0
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Enums
	// --------------------------------------------------
	/**
	 * UserDefinedEnum Config_KeyconfigItems.Config_KeyconfigItems
	 */
	enum class EConfig_KeyconfigItems : uint8_t
	{
		Config_KeyconfigItemsNewEnumerator14  = 0,
		Config_KeyconfigItemsNewEnumerator0   = 1,
		Config_KeyconfigItemsNewEnumerator1   = 2,
		Config_KeyconfigItemsNewEnumerator2   = 3,
		Config_KeyconfigItemsNewEnumerator3   = 4,
		Config_KeyconfigItemsNewEnumerator4   = 5,
		Config_KeyconfigItemsNewEnumerator6   = 6,
		Config_KeyconfigItemsNewEnumerator7   = 7,
		Config_KeyconfigItemsNewEnumerator8   = 8,
		Config_KeyconfigItemsNewEnumerator9   = 9,
		Config_KeyconfigItemsNewEnumerator10  = 10,
		Config_KeyconfigItemsNewEnumerator12  = 11,
		Config_KeyconfigItemsNewEnumerator11  = 12,
		Config_KeyconfigItemsNewEnumerator15  = 13,
		Config_KeyconfigItemsNewEnumerator13  = 14,
		Config_KeyconfigItemsNewEnumerator16  = 15,
		Config_KeyconfigItemsNewEnumerator17  = 16,
		Config_KeyconfigItemsNewEnumerator18  = 17,
		Config_KeyconfigItemsNewEnumerator19  = 18,
		Config_KeyconfigItemsNewEnumerator20  = 19,
		Config_KeyconfigItemsNewEnumerator21  = 20,
		Config_KeyconfigItemsNewEnumerator22  = 21,
		Config_KeyconfigItemsNewEnumerator23  = 22,
		Config_KeyconfigItemsNewEnumerator24  = 23,
		Config_KeyconfigItemsNewEnumerator25  = 24,
		Config_KeyconfigItemsNewEnumerator26  = 25,
		Config_KeyconfigItemsNewEnumerator27  = 26,
		Config_KeyconfigItemsNewEnumerator29  = 27,
		Config_KeyconfigItemsNewEnumerator30  = 28,
		Config_KeyconfigItemsNewEnumerator33  = 29,
		Config_KeyconfigItemsNewEnumerator37  = 30,
		Config_KeyconfigItemsNewEnumerator32  = 31,
		Config_KeyconfigItemsNewEnumerator31  = 32,
		Config_KeyconfigItemsNewEnumerator34  = 33,
		Config_KeyconfigItemsNewEnumerator35  = 34,
		Config_KeyconfigItemsNewEnumerator38  = 35,
		Config_KeyconfigItemsNewEnumerator39  = 36,
		Config_KeyconfigItemsNewEnumerator40  = 37,
		Config_KeyconfigItemsNewEnumerator42  = 38,
		Config_KeyconfigItemsNewEnumerator43  = 39,
		Config_KeyconfigItemsNewEnumerator44  = 40,
		Config_KeyconfigItemsNewEnumerator45  = 41,
		Config_KeyconfigItemsNewEnumerator47  = 42,
		Config_KeyconfigItemsNewEnumerator48  = 43,
		Config_KeyconfigItemsNewEnumerator49  = 44,
		Config_KeyconfigItemsNewEnumerator50  = 45,
		Config_KeyconfigItemsNewEnumerator51  = 46,
		Config_KeyconfigItemsNewEnumerator52  = 47,
		Config_KeyconfigItemsNewEnumerator53  = 48,
		Config_KeyconfigItemsNewEnumerator54  = 49,
		Config_KeyconfigItemsNewEnumerator55  = 50,
		Config_KeyconfigItemsNewEnumerator57  = 51,
		Config_KeyconfigItemsNewEnumerator58  = 52,
		Config_KeyconfigItemsNewEnumerator59  = 53,
		Config_KeyconfigItemsNewEnumerator60  = 54,
		Config_KeyconfigItemsNewEnumerator61  = 55,
		Config_KeyconfigItemsNewEnumerator69  = 56,
		Config_KeyconfigItemsNewEnumerator70  = 57,
		Config_KeyconfigItemsNewEnumerator63  = 58,
		Config_KeyconfigItemsNewEnumerator62  = 59,
		Config_KeyconfigItemsNewEnumerator64  = 60,
		Config_KeyconfigItemsNewEnumerator65  = 61,
		Config_KeyconfigItemsNewEnumerator66  = 62,
		Config_KeyconfigItemsNewEnumerator71  = 63,
		Config_KeyconfigItemsNewEnumerator72  = 64,
		Config_KeyconfigItemsNewEnumerator73  = 65,
		Config_KeyconfigItemsNewEnumerator74  = 66,
		Config_KeyconfigItemsNewEnumerator75  = 67,
		Config_KeyconfigItemsNewEnumerator76  = 68,
		Config_KeyconfigItemsNewEnumerator77  = 69,
		Config_KeyconfigItemsNewEnumerator78  = 70,
		Config_KeyconfigItemsNewEnumerator79  = 71,
		Config_KeyconfigItemsNewEnumerator80  = 72,
		Config_KeyconfigItemsNewEnumerator81  = 73,
		Config_KeyconfigItemsNewEnumerator82  = 74,
		Config_KeyconfigItemsNewEnumerator83  = 75,
		Config_KeyconfigItemsNewEnumerator84  = 76,
		Config_KeyconfigItemsNewEnumerator85  = 77,
		Config_KeyconfigItemsNewEnumerator86  = 78,
		Config_KeyconfigItemsNewEnumerator87  = 79,
		Config_KeyconfigItemsNewEnumerator88  = 80,
		Config_KeyconfigItemsNewEnumerator89  = 81,
		Config_KeyconfigItemsNewEnumerator90  = 82,
		Config_KeyconfigItemsNewEnumerator91  = 83,
		Config_KeyconfigItemsNewEnumerator92  = 84,
		Config_KeyconfigItemsNewEnumerator93  = 85,
		Config_KeyconfigItemsNewEnumerator94  = 86,
		Config_KeyconfigItemsNewEnumerator95  = 87,
		Config_KeyconfigItemsNewEnumerator96  = 88,
		Config_KeyconfigItemsNewEnumerator97  = 89,
		Config_KeyconfigItemsNewEnumerator98  = 90,
		Config_KeyconfigItemsNewEnumerator99  = 91,
		Config_KeyconfigItemsNewEnumerator100 = 92,
		Config_KeyconfigItemsNewEnumerator101 = 93,
		Config_KeyconfigItemsNewEnumerator102 = 94,
		Config_KeyconfigItemsNewEnumerator103 = 95,
		Config_KeyconfigItemsNewEnumerator104 = 96,
		Config_KeyconfigItemsNewEnumerator105 = 97,
		Config_KeyconfigItemsNewEnumerator106 = 98,
		Config_KeyconfigItemsNewEnumerator107 = 99,
		Config_KeyconfigItemsNewEnumerator108 = 100,
		Config_KeyconfigItemsNewEnumerator109 = 101,
		Config_KeyconfigItemsNewEnumerator110 = 102,
		Config_KeyconfigItemsNewEnumerator111 = 103,
		Config_KeyconfigItemsNewEnumerator112 = 104,
		Config_KeyconfigItemsNewEnumerator113 = 105,
		Config_KeyconfigItemsNewEnumerator114 = 106,
		Config_KeyconfigItemsNewEnumerator115 = 107,
		Config_KeyconfigItemsNewEnumerator116 = 108,
		Config_KeyconfigItemsNewEnumerator117 = 109,
		Config_KeyconfigItemsNewEnumerator118 = 110,
		Config_KeyconfigItemsNewEnumerator119 = 111,
		Config_KeyconfigItemsNewEnumerator120 = 112,
		Config_KeyconfigItemsNewEnumerator121 = 113,
		Config_KeyconfigItemsNewEnumerator122 = 114,
		Config_KeyconfigItemsNewEnumerator123 = 115,
		Config_KeyconfigItemsNewEnumerator124 = 116,
		Config_KeyconfigItemsNewEnumerator125 = 117,
		Config_KeyconfigItemsNewEnumerator126 = 118,
		Config_KeyconfigItemsNewEnumerator127 = 119,
		Config_KeyconfigItemsNewEnumerator128 = 120,
		Config_KeyconfigItemsNewEnumerator129 = 121,
		Config_KeyconfigItemsNewEnumerator130 = 122,
		Config_KeyconfigItemsNewEnumerator131 = 123,
		Config_KeyconfigItemsNewEnumerator132 = 124,
		Config_KeyconfigItemsNewEnumerator133 = 125,
		Config_KeyconfigItemsNewEnumerator134 = 126,
		Config_KeyconfigItemsConfig_MAX       = 127
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
