#pragma once

 

// Package: BP_EF_BPSet_SpawnGround_Point

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "SkyBlue_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_EF_BPSet_SpawnGround_Point.BP_EF_BPSet_SpawnGround_Point_C.ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point
// 0x05F0 (0x05F0 - 0x0000)
struct BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_6;                               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_7;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_8;                               // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_9;                               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_10;                              // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_11;                              // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_12;                              // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_13;                              // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_14;                              // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_15;                              // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_16;                              // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_17;                              // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_18;                              // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_19;                              // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_20;                              // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_21;                              // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_22;                              // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0063(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable_2;                     // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7785[0x3];                                     // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_23;                              // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPhysicalSurface                              Temp_byte_Variable;                                // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7786[0x3];                                     // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0070(0x0010)(ConstParm, ReferenceParm)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0084(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0090(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_2;                 // 0x00A0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FFloor_ReturnValue;                       // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FFloor_ReturnValue_1;                     // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7787[0x3];                                     // 0x00C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue;           // 0x00C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable_2;               // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7788[0x2];                                     // 0x00D2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_2VectorDistance_NewParam;                 // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7789[0x3];                                     // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x00F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0100(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_778A[0x4];                                     // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array;                            // 0x0110(0x0010)(ConstParm, ReferenceParm)
	struct FVector                                CallFunc_GetActorScale3D_ReturnValue;              // 0x0120(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x012C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue_1;        // 0x0138(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable_3;               // 0x0144(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_778B[0x3];                                     // 0x0145(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0148(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0154(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue_1;       // 0x0160(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_2;           // 0x016C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_3;           // 0x0178(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_3;                     // 0x0184(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_778C[0x3];                                     // 0x0185(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_24;                              // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_25;                              // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_26;                              // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_27;                              // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingleForObjects_OutHit;         // 0x0198(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingleForObjects_ReturnValue;    // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0221(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0222(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_778D[0x1];                                     // 0x0223(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x022C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0238(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0244(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0250(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_778E[0x4];                                     // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0270(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0280(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0284(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x028C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0298(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotFromZ_ReturnValue;                 // 0x02A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x02B0(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_28;                              // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBEffectVisibleType                          CallFunc_GetEffectVisibleType_ReturnValue;         // 0x0304(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_778F[0x3];                                     // 0x0305(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default;                             // 0x0308(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7790[0x4];                                     // 0x030C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBSpawnEmitterAtLocationParam         K2Node_MakeStruct_SBSpawnEmitterAtLocationParam;   // 0x0310(0x0048)(NoDestructor)
	class UParticleSystem*                        CallFunc_Array_Get_Item;                           // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0360(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSBSpawnEmitterAtLocationParam         K2Node_MakeStruct_SBSpawnEmitterAtLocationParam_1; // 0x0368(0x0048)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x03B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7791[0x7];                                     // 0x03B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue_1;     // 0x03B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7792[0x3];                                     // 0x03C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult;       // 0x03C4(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x044C(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x04D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7793[0x3];                                     // 0x04D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult_1;     // 0x04D8(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult_1;     // 0x0560(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x05E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point) == 0x000010, "Wrong alignment on BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point");
static_assert(sizeof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point) == 0x0005F0, "Wrong size on BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, EntryPoint) == 0x000000, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable) == 0x000004, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_1) == 0x000008, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_2) == 0x00000C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_3) == 0x000010, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_4) == 0x000014, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_5) == 0x000018, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_6) == 0x00001C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_6' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_7) == 0x000020, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_7' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_8) == 0x000024, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_8' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_9) == 0x000028, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_9' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_10) == 0x00002C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_10' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_11) == 0x000030, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_11' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_12) == 0x000034, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_12' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_13) == 0x000038, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_13' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_14) == 0x00003C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_14' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_15) == 0x000040, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_15' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_16) == 0x000044, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_16' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_17) == 0x000048, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_17' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_18) == 0x00004C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_18' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_19) == 0x000050, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_19' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_20) == 0x000054, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_20' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_21) == 0x000058, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_21' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_22) == 0x00005C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_22' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_Has_Been_Initd_Variable) == 0x000060, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_IsClosed_Variable) == 0x000061, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_IsClosed_Variable_1) == 0x000062, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_Has_Been_Initd_Variable_1) == 0x000063, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_IsClosed_Variable_2) == 0x000064, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_IsClosed_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_23) == 0x000068, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_23' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_byte_Variable) == 0x00006C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_object_Variable) == 0x000070, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, K2Node_Event_DeltaSeconds) == 0x000080, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_MakeVector_ReturnValue) == 0x000084, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_MakeVector_ReturnValue_1) == 0x000090, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00009C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_MakeVector_ReturnValue_2) == 0x0000A0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_MakeVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_FFloor_ReturnValue) == 0x0000AC, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_FFloor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_FFloor_ReturnValue_1) == 0x0000B0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_FFloor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x0000B4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Subtract_IntInt_ReturnValue) == 0x0000B8, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000BC, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000C0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_FindLookAtRotation_ReturnValue) == 0x0000C4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_FindLookAtRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, K2Node_SwitchInteger_CmpSuccess) == 0x0000D0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_Has_Been_Initd_Variable_2) == 0x0000D1, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_Has_Been_Initd_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000D4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Add_VectorVector_ReturnValue) == 0x0000E0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_2VectorDistance_NewParam) == 0x0000EC, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_2VectorDistance_NewParam' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0000F0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Add_VectorVector_ReturnValue_1) == 0x0000F4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000100, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, K2Node_MakeArray_Array) == 0x000110, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_GetActorScale3D_ReturnValue) == 0x000120, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_GetActorScale3D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Multiply_VectorVector_ReturnValue) == 0x00012C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_GetActorRotation_ReturnValue_1) == 0x000138, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_GetActorRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_Has_Been_Initd_Variable_3) == 0x000144, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_Has_Been_Initd_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_GetForwardVector_ReturnValue) == 0x000148, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000154, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Multiply_VectorFloat_ReturnValue_1) == 0x000160, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Multiply_VectorFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Add_VectorVector_ReturnValue_2) == 0x00016C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Add_VectorVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Add_VectorVector_ReturnValue_3) == 0x000178, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Add_VectorVector_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_bool_IsClosed_Variable_3) == 0x000184, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_bool_IsClosed_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_24) == 0x000188, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_24' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_25) == 0x00018C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_25' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_26) == 0x000190, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_26' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_27) == 0x000194, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_27' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_LineTraceSingleForObjects_OutHit) == 0x000198, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_LineTraceSingleForObjects_OutHit' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_LineTraceSingleForObjects_ReturnValue) == 0x000220, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_LineTraceSingleForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_bBlockingHit) == 0x000221, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_bInitialOverlap) == 0x000222, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_Time) == 0x000224, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_Distance) == 0x000228, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_Location) == 0x00022C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_ImpactPoint) == 0x000238, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_Normal) == 0x000244, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_ImpactNormal) == 0x000250, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_PhysMat) == 0x000260, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_HitActor) == 0x000268, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_HitComponent) == 0x000270, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_HitBoneName) == 0x000278, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_HitItem) == 0x000280, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_ElementIndex) == 0x000284, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_FaceIndex) == 0x000288, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_TraceStart) == 0x00028C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BreakHitResult_TraceEnd) == 0x000298, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_MakeRotFromZ_ReturnValue) == 0x0002A4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_MakeRotFromZ_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_MakeTransform_ReturnValue) == 0x0002B0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0002E0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x0002E8, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_FinishSpawningActor_ReturnValue) == 0x0002F0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x0002F8, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, Temp_int_Variable_28) == 0x000300, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::Temp_int_Variable_28' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_GetEffectVisibleType_ReturnValue) == 0x000304, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_GetEffectVisibleType_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, K2Node_Select_Default) == 0x000308, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, K2Node_MakeStruct_SBSpawnEmitterAtLocationParam) == 0x000310, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::K2Node_MakeStruct_SBSpawnEmitterAtLocationParam' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_Array_Get_Item) == 0x000358, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000360, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, K2Node_MakeStruct_SBSpawnEmitterAtLocationParam_1) == 0x000368, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::K2Node_MakeStruct_SBSpawnEmitterAtLocationParam_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_IsValid_ReturnValue) == 0x0003B0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_SpawnEmitterAtLocation_ReturnValue_1) == 0x0003B8, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_SpawnEmitterAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_IsValid_ReturnValue_1) == 0x0003C0, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_SetWorldRotation_SweepHitResult) == 0x0003C4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_SetWorldRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x00044C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_IsValid_ReturnValue_2) == 0x0004D4, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_SetWorldLocation_SweepHitResult_1) == 0x0004D8, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_SetWorldLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_K2_SetWorldRotation_SweepHitResult_1) == 0x000560, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_K2_SetWorldRotation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point, CallFunc_IsValid_ReturnValue_3) == 0x0005E8, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ExecuteUbergraph_BP_EF_BPSet_SpawnGround_Point::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");

// Function BP_EF_BPSet_SpawnGround_Point.BP_EF_BPSet_SpawnGround_Point_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick");
static_assert(sizeof(BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick) == 0x000004, "Wrong size on BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_EF_BPSet_SpawnGround_Point_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_EF_BPSet_SpawnGround_Point.BP_EF_BPSet_SpawnGround_Point_C.2VectorDistance
// 0x0058 (0x0058 - 0x0000)
struct BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance final
{
public:
	struct FVector                                A;                                                 // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                B;                                                 // 0x000C(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NewParam;                                          // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X_1;                          // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y_1;                          // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z_1;                          // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Square_ReturnValue;                       // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Square_ReturnValue_1;                     // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Square_ReturnValue_2;                     // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue_1;             // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Sqrt_ReturnValue;                         // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance) == 0x000004, "Wrong alignment on BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance");
static_assert(sizeof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance) == 0x000058, "Wrong size on BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, A) == 0x000000, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::A' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, B) == 0x00000C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::B' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, NewParam) == 0x000018, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::NewParam' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_BreakVector_X) == 0x00001C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_BreakVector_Y) == 0x000020, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_BreakVector_Z) == 0x000024, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_BreakVector_X_1) == 0x000028, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_BreakVector_Y_1) == 0x00002C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_BreakVector_Z_1) == 0x000030, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000034, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000038, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Square_ReturnValue) == 0x00003C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Square_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Square_ReturnValue_1) == 0x000040, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Square_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x000044, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Square_ReturnValue_2) == 0x000048, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Square_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Add_FloatFloat_ReturnValue) == 0x00004C, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Add_FloatFloat_ReturnValue_1) == 0x000050, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Add_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance, CallFunc_Sqrt_ReturnValue) == 0x000054, "Member 'BP_EF_BPSet_SpawnGround_Point_C_TwoVectorDistance::CallFunc_Sqrt_ReturnValue' has a wrong offset!");

}

