#pragma once

 

// Package: BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos

#include "Basic.hpp"

#include "SkyBlue_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos.BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C.ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos
// 0x01A8 (0x01A8 - 0x0000)
struct BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotifyDeletedMountsToLogAndMessage_OutIsMessageShowed; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotifyDeletedImaginesToLogAndMessage_OutIsMessageShowed; // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotifyDeletedCostumesToLogAndMessage_OutIsMessageShowed; // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotifyDecayedWeaponsToLogAndMessage_OutIsMessageShowed; // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsStandalone_ReturnValue;                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9174[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBPlayerState*                         CallFunc_GetSBPlayerState_ReturnValue;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9175[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBPlayerStorageComponent*              CallFunc_GetPlayerStorageComponent_ReturnValue;    // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9176[0x3];                                     // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FSBExpiredEquipmentData& InExpiredEquipmentData)> K2Node_CreateDelegate_OutputDelegate;              // 0x002C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x003C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_9177[0x4];                                     // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0050(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FSBExpiredEquipmentData                K2Node_CustomEvent_InExpiredEquipmentData;         // 0x0058(0x0130)(ConstParm)
	bool                                          CallFunc_GetSystemMessageManager_IsValid;          // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9178[0x7];                                     // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                CallFunc_GetSystemMessageManager_ReturnValue;      // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSystemMessageShowingOrStandby_ReturnValue; // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9179[0x3];                                     // 0x0199(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_PlaySE_ReturnValue;                       // 0x019C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos) == 0x000008, "Wrong alignment on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos");
static_assert(sizeof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos) == 0x0001A8, "Wrong size on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, EntryPoint) == 0x000000, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_NotifyDeletedMountsToLogAndMessage_OutIsMessageShowed) == 0x000004, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_NotifyDeletedMountsToLogAndMessage_OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_NotifyDeletedImaginesToLogAndMessage_OutIsMessageShowed) == 0x000005, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_NotifyDeletedImaginesToLogAndMessage_OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_NotifyDeletedCostumesToLogAndMessage_OutIsMessageShowed) == 0x000006, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_NotifyDeletedCostumesToLogAndMessage_OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_NotifyDecayedWeaponsToLogAndMessage_OutIsMessageShowed) == 0x000007, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_NotifyDecayedWeaponsToLogAndMessage_OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_IsStandalone_ReturnValue) == 0x000008, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_IsStandalone_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_GetSBPlayerState_ReturnValue) == 0x000010, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_GetSBPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_GetPlayerStorageComponent_ReturnValue) == 0x000020, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_GetPlayerStorageComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_IsValid_ReturnValue_1) == 0x000028, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, K2Node_CreateDelegate_OutputDelegate) == 0x00002C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, K2Node_CreateDelegate_OutputDelegate_1) == 0x00003C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000050, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, K2Node_CustomEvent_InExpiredEquipmentData) == 0x000058, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::K2Node_CustomEvent_InExpiredEquipmentData' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_GetSystemMessageManager_IsValid) == 0x000188, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_GetSystemMessageManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_GetSystemMessageManager_ReturnValue) == 0x000190, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_GetSystemMessageManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_IsSystemMessageShowingOrStandby_ReturnValue) == 0x000198, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_IsSystemMessageShowingOrStandby_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_PlaySE_ReturnValue) == 0x00019C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_PlaySE_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos, CallFunc_BooleanAND_ReturnValue) == 0x0001A0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_ExecuteUbergraph_BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos.BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C.OnGetExpiredEquipmentDataEvent
// 0x0130 (0x0130 - 0x0000)
struct BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent final
{
public:
	struct FSBExpiredEquipmentData                InExpiredEquipmentData;                            // 0x0000(0x0130)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent) == 0x000008, "Wrong alignment on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent");
static_assert(sizeof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent) == 0x000130, "Wrong size on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent, InExpiredEquipmentData) == 0x000000, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_OnGetExpiredEquipmentDataEvent::InExpiredEquipmentData' has a wrong offset!");

// Function BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos.BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C.NotifyDecayedWeaponsToLogAndMessage
// 0x0370 (0x0370 - 0x0000)
struct BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage final
{
public:
	TArray<struct FSBDecayedWeaponData>           InDecayedWeaponDatas;                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          OutIsMessageShowed;                                // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_917A[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 TmpDecayedWeaponName;                              // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 TmpExpiredWeaponName;                              // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         TmpExpiredWeaponId;                                // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TmpDecayedWeaponId;                                // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowable;                             // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_917B[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                TmpSystemMessageManager;                           // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBMasterDataManager*                   TmpMasterDataManager;                              // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowed;                               // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_917C[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSBDecayedWeaponData>           TmpDecayedWeaponDatas;                             // 0x0060(0x0010)(Edit, BlueprintVisible)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_917D[0x3];                                     // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_917E[0x4];                                     // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBDecayedWeaponData                   CallFunc_Array_Get_Item;                           // 0x0088(0x0038)()
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00C5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00C6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetMasterDataManager_IsValid;             // 0x00C7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class USBMasterDataManager*                   CallFunc_GetMasterDataManager_ReturnValue;         // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSystemMessageManager_IsValid;          // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_917F[0x6];                                     // 0x00D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                CallFunc_GetSystemMessageManager_ReturnValue;      // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00E0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00F8(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0138(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0150(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0190(0x0010)(ReferenceParm)
	bool                                          CallFunc_GetWeaponMasterData_IsExists;             // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9180[0x7];                                     // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBWeaponMasterData                    CallFunc_GetWeaponMasterData_ReturnValue;          // 0x01A8(0x00B0)()
	bool                                          CallFunc_GetWeaponMasterData_IsExists_1;           // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9181[0x7];                                     // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBWeaponMasterData                    CallFunc_GetWeaponMasterData_ReturnValue_1;        // 0x0260(0x00B0)()
	class FString                                 CallFunc_GetWeaponText_ReturnValue;                // 0x0310(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetWeaponText_ReturnValue_1;              // 0x0320(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetTextFromAssetByName_ReturnValue;       // 0x0330(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x0340(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0358(0x0018)()
};
static_assert(alignof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage) == 0x000008, "Wrong alignment on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage");
static_assert(sizeof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage) == 0x000370, "Wrong size on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, InDecayedWeaponDatas) == 0x000000, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::InDecayedWeaponDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, OutIsMessageShowed) == 0x000010, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpDecayedWeaponName) == 0x000018, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpDecayedWeaponName' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpExpiredWeaponName) == 0x000028, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpExpiredWeaponName' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpExpiredWeaponId) == 0x000038, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpExpiredWeaponId' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpDecayedWeaponId) == 0x00003C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpDecayedWeaponId' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, bTmpIsMessageShowable) == 0x000040, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::bTmpIsMessageShowable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpSystemMessageManager) == 0x000048, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpSystemMessageManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpMasterDataManager) == 0x000050, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpMasterDataManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, bTmpIsMessageShowed) == 0x000058, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::bTmpIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, TmpDecayedWeaponDatas) == 0x000060, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::TmpDecayedWeaponDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Array_Length_ReturnValue) == 0x000070, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Greater_IntInt_ReturnValue) == 0x000074, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, Temp_int_Array_Index_Variable) == 0x000078, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, Temp_int_Loop_Counter_Variable) == 0x00007C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Add_IntInt_ReturnValue) == 0x000080, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Array_Get_Item) == 0x000088, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Array_Length_ReturnValue_1) == 0x0000C0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Less_IntInt_ReturnValue) == 0x0000C4, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_IsValid_ReturnValue) == 0x0000C5, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_IsValid_ReturnValue_1) == 0x0000C6, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetMasterDataManager_IsValid) == 0x0000C7, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetMasterDataManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetMasterDataManager_ReturnValue) == 0x0000C8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetMasterDataManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_BooleanAND_ReturnValue) == 0x0000D0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetSystemMessageManager_IsValid) == 0x0000D1, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetSystemMessageManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetSystemMessageManager_ReturnValue) == 0x0000D8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetSystemMessageManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue) == 0x0000E0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, K2Node_MakeStruct_FormatArgumentData) == 0x0000F8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue_1) == 0x000138, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, K2Node_MakeStruct_FormatArgumentData_1) == 0x000150, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, K2Node_MakeArray_Array) == 0x000190, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetWeaponMasterData_IsExists) == 0x0001A0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetWeaponMasterData_IsExists' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetWeaponMasterData_ReturnValue) == 0x0001A8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetWeaponMasterData_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetWeaponMasterData_IsExists_1) == 0x000258, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetWeaponMasterData_IsExists_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetWeaponMasterData_ReturnValue_1) == 0x000260, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetWeaponMasterData_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetWeaponText_ReturnValue) == 0x000310, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetWeaponText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetWeaponText_ReturnValue_1) == 0x000320, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetWeaponText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_GetTextFromAssetByName_ReturnValue) == 0x000330, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_GetTextFromAssetByName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue_2) == 0x000340, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage, CallFunc_Format_ReturnValue) == 0x000358, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDecayedWeaponsToLogAndMessage::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos.BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C.NotifyDeletedCostumesToLogAndMessage
// 0x0228 (0x0228 - 0x0000)
struct BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage final
{
public:
	TArray<struct FSBDeletedCostumeData>          InDeletedCostumeDatas;                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          OutIsMessageShowed;                                // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9182[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 TmpExpiredCostumeName;                             // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         TmpExpiredCostumeId;                               // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowable;                             // 0x002C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9183[0x3];                                     // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                TmpSystemMessageManager;                           // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBMasterDataManager*                   TmpMasterDataManager;                              // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowed;                               // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9184[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSBDeletedCostumeData>          TmpDeletedCostumeDatas;                            // 0x0048(0x0010)(Edit, BlueprintVisible)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9185[0x3];                                     // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9186[0x4];                                     // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0070(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0088(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_BP_FindCostumeMaster_IsExist;             // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9187[0x7];                                     // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBMasterCostume                       CallFunc_BP_FindCostumeMaster_ReturnValue;         // 0x00D0(0x0088)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0158(0x0010)(ReferenceParm)
	class FString                                 CallFunc_GetCostumeText_ReturnValue;               // 0x0168(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FSBDeletedCostumeData                  CallFunc_Array_Get_Item;                           // 0x0178(0x0048)()
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9188[0x3];                                     // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetTextFromAssetByName_ReturnValue;       // 0x01C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x01D8(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01F0(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0209(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetMasterDataManager_IsValid;             // 0x020A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9189[0x5];                                     // 0x020B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USBMasterDataManager*                   CallFunc_GetMasterDataManager_ReturnValue;         // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSystemMessageManager_IsValid;          // 0x0219(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_918A[0x6];                                     // 0x021A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                CallFunc_GetSystemMessageManager_ReturnValue;      // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage) == 0x000008, "Wrong alignment on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage");
static_assert(sizeof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage) == 0x000228, "Wrong size on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, InDeletedCostumeDatas) == 0x000000, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::InDeletedCostumeDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, OutIsMessageShowed) == 0x000010, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, TmpExpiredCostumeName) == 0x000018, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::TmpExpiredCostumeName' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, TmpExpiredCostumeId) == 0x000028, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::TmpExpiredCostumeId' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, bTmpIsMessageShowable) == 0x00002C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::bTmpIsMessageShowable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, TmpSystemMessageManager) == 0x000030, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::TmpSystemMessageManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, TmpMasterDataManager) == 0x000038, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::TmpMasterDataManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, bTmpIsMessageShowed) == 0x000040, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::bTmpIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, TmpDeletedCostumeDatas) == 0x000048, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::TmpDeletedCostumeDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, Temp_int_Array_Index_Variable) == 0x00005C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Greater_IntInt_ReturnValue) == 0x000060, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, Temp_int_Loop_Counter_Variable) == 0x000064, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Add_IntInt_ReturnValue) == 0x000068, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue) == 0x000070, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, K2Node_MakeStruct_FormatArgumentData) == 0x000088, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_BP_FindCostumeMaster_IsExist) == 0x0000C8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_BP_FindCostumeMaster_IsExist' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_BP_FindCostumeMaster_ReturnValue) == 0x0000D0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_BP_FindCostumeMaster_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, K2Node_MakeArray_Array) == 0x000158, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_GetCostumeText_ReturnValue) == 0x000168, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_GetCostumeText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Array_Get_Item) == 0x000178, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Array_Length_ReturnValue_1) == 0x0001C0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Less_IntInt_ReturnValue) == 0x0001C4, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_GetTextFromAssetByName_ReturnValue) == 0x0001C8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_GetTextFromAssetByName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0001D8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_Format_ReturnValue) == 0x0001F0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_IsValid_ReturnValue) == 0x000208, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_IsValid_ReturnValue_1) == 0x000209, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_GetMasterDataManager_IsValid) == 0x00020A, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_GetMasterDataManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_GetMasterDataManager_ReturnValue) == 0x000210, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_GetMasterDataManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_BooleanAND_ReturnValue) == 0x000218, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_GetSystemMessageManager_IsValid) == 0x000219, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_GetSystemMessageManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage, CallFunc_GetSystemMessageManager_ReturnValue) == 0x000220, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedCostumesToLogAndMessage::CallFunc_GetSystemMessageManager_ReturnValue' has a wrong offset!");

// Function BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos.BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C.NotifyDeletedImaginesToLogAndMessage
// 0x0240 (0x0240 - 0x0000)
struct BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage final
{
public:
	TArray<struct FSBDeletedImagineData>          InDeletedImagineDatas;                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          OutIsMessageShowed;                                // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_918B[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 TmpExpiredImagineName;                             // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         TmpExpiredImagineId;                               // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowable;                             // 0x002C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_918C[0x3];                                     // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                TmpSystemMessageManager;                           // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBMasterDataManager*                   TmpMasterDataManager;                              // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowed;                               // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_918D[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSBDeletedImagineData>          TmpDeletedImagineDatas;                            // 0x0048(0x0010)(Edit, BlueprintVisible)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_918E[0x3];                                     // 0x005D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_918F[0x4];                                     // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBDeletedImagineData                  CallFunc_Array_Get_Item;                           // 0x0068(0x0038)()
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9190[0x3];                                     // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00B0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00C8(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_FindMasterImagineData_IsExists;           // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9191[0x7];                                     // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBMasterImagine                       CallFunc_FindMasterImagineData_ReturnValue;        // 0x0110(0x00B0)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01C0(0x0010)(ReferenceParm)
	class FString                                 CallFunc_GetMasterImagineText_ReturnValue;         // 0x01D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetTextFromAssetByName_ReturnValue;       // 0x01E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x01F0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0208(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0221(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetMasterDataManager_IsValid;             // 0x0222(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9192[0x5];                                     // 0x0223(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USBMasterDataManager*                   CallFunc_GetMasterDataManager_ReturnValue;         // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSystemMessageManager_IsValid;          // 0x0231(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9193[0x6];                                     // 0x0232(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                CallFunc_GetSystemMessageManager_ReturnValue;      // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage) == 0x000008, "Wrong alignment on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage");
static_assert(sizeof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage) == 0x000240, "Wrong size on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, InDeletedImagineDatas) == 0x000000, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::InDeletedImagineDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, OutIsMessageShowed) == 0x000010, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, TmpExpiredImagineName) == 0x000018, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::TmpExpiredImagineName' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, TmpExpiredImagineId) == 0x000028, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::TmpExpiredImagineId' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, bTmpIsMessageShowable) == 0x00002C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::bTmpIsMessageShowable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, TmpSystemMessageManager) == 0x000030, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::TmpSystemMessageManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, TmpMasterDataManager) == 0x000038, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::TmpMasterDataManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, bTmpIsMessageShowed) == 0x000040, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::bTmpIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, TmpDeletedImagineDatas) == 0x000048, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::TmpDeletedImagineDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Greater_IntInt_ReturnValue) == 0x00005C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, Temp_int_Array_Index_Variable) == 0x000060, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Array_Get_Item) == 0x000068, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Array_Length_ReturnValue_1) == 0x0000A0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, Temp_int_Loop_Counter_Variable) == 0x0000A4, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Less_IntInt_ReturnValue) == 0x0000A8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Add_IntInt_ReturnValue) == 0x0000AC, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue) == 0x0000B0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, K2Node_MakeStruct_FormatArgumentData) == 0x0000C8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_FindMasterImagineData_IsExists) == 0x000108, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_FindMasterImagineData_IsExists' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_FindMasterImagineData_ReturnValue) == 0x000110, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_FindMasterImagineData_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, K2Node_MakeArray_Array) == 0x0001C0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_GetMasterImagineText_ReturnValue) == 0x0001D0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_GetMasterImagineText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_GetTextFromAssetByName_ReturnValue) == 0x0001E0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_GetTextFromAssetByName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0001F0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_Format_ReturnValue) == 0x000208, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_IsValid_ReturnValue) == 0x000220, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_IsValid_ReturnValue_1) == 0x000221, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_GetMasterDataManager_IsValid) == 0x000222, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_GetMasterDataManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_GetMasterDataManager_ReturnValue) == 0x000228, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_GetMasterDataManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_BooleanAND_ReturnValue) == 0x000230, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_GetSystemMessageManager_IsValid) == 0x000231, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_GetSystemMessageManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage, CallFunc_GetSystemMessageManager_ReturnValue) == 0x000238, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedImaginesToLogAndMessage::CallFunc_GetSystemMessageManager_ReturnValue' has a wrong offset!");

// Function BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos.BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C.NotifyDeletedMountsToLogAndMessage
// 0x0200 (0x0200 - 0x0000)
struct BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage final
{
public:
	TArray<struct FSBDeletedMountData>            InDeletedMountDatas;                               // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          OutIsMessageShowed;                                // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9194[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 TmpExpiredMountName;                               // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         TmpExpiredMountId;                                 // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowable;                             // 0x002C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9195[0x3];                                     // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                TmpSystemMessageManager;                           // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBMasterDataManager*                   TmpMasterDataManager;                              // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTmpIsMessageShowed;                               // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9196[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSBDeletedMountData>            TmpDeletedMountDatas;                              // 0x0048(0x0010)(Edit, BlueprintVisible)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9197[0x3];                                     // 0x005D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9198[0x4];                                     // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBDeletedMountData                    CallFunc_Array_Get_Item;                           // 0x0068(0x0038)()
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9199[0x3];                                     // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00B0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00C8(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_BP_FindMasterMountImagineData_bOutExist;  // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_919A[0x7];                                     // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBMasterMountImagine                  CallFunc_BP_FindMasterMountImagineData_ReturnValue; // 0x0110(0x0070)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0180(0x0010)(ReferenceParm)
	class FString                                 CallFunc_GetMasterMountImagineText_ReturnValue;    // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetTextFromAssetByName_ReturnValue;       // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x01B0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01C8(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetMasterDataManager_IsValid;             // 0x01E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_919B[0x5];                                     // 0x01E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USBMasterDataManager*                   CallFunc_GetMasterDataManager_ReturnValue;         // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSystemMessageManager_IsValid;          // 0x01F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_919C[0x6];                                     // 0x01F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USBSystemMessageManager*                CallFunc_GetSystemMessageManager_ReturnValue;      // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage) == 0x000008, "Wrong alignment on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage");
static_assert(sizeof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage) == 0x000200, "Wrong size on BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, InDeletedMountDatas) == 0x000000, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::InDeletedMountDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, OutIsMessageShowed) == 0x000010, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::OutIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, TmpExpiredMountName) == 0x000018, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::TmpExpiredMountName' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, TmpExpiredMountId) == 0x000028, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::TmpExpiredMountId' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, bTmpIsMessageShowable) == 0x00002C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::bTmpIsMessageShowable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, TmpSystemMessageManager) == 0x000030, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::TmpSystemMessageManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, TmpMasterDataManager) == 0x000038, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::TmpMasterDataManager' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, bTmpIsMessageShowed) == 0x000040, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::bTmpIsMessageShowed' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, TmpDeletedMountDatas) == 0x000048, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::TmpDeletedMountDatas' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Greater_IntInt_ReturnValue) == 0x00005C, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, Temp_int_Array_Index_Variable) == 0x000060, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Array_Get_Item) == 0x000068, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Array_Length_ReturnValue_1) == 0x0000A0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, Temp_int_Loop_Counter_Variable) == 0x0000A4, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Less_IntInt_ReturnValue) == 0x0000A8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Add_IntInt_ReturnValue) == 0x0000AC, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue) == 0x0000B0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, K2Node_MakeStruct_FormatArgumentData) == 0x0000C8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_BP_FindMasterMountImagineData_bOutExist) == 0x000108, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_BP_FindMasterMountImagineData_bOutExist' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_BP_FindMasterMountImagineData_ReturnValue) == 0x000110, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_BP_FindMasterMountImagineData_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, K2Node_MakeArray_Array) == 0x000180, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_GetMasterMountImagineText_ReturnValue) == 0x000190, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_GetMasterMountImagineText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_GetTextFromAssetByName_ReturnValue) == 0x0001A0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_GetTextFromAssetByName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0001B0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_Format_ReturnValue) == 0x0001C8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_IsValid_ReturnValue) == 0x0001E0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_IsValid_ReturnValue_1) == 0x0001E1, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_GetMasterDataManager_IsValid) == 0x0001E2, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_GetMasterDataManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_GetMasterDataManager_ReturnValue) == 0x0001E8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_GetMasterDataManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_BooleanAND_ReturnValue) == 0x0001F0, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_GetSystemMessageManager_IsValid) == 0x0001F1, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_GetSystemMessageManager_IsValid' has a wrong offset!");
static_assert(offsetof(BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage, CallFunc_GetSystemMessageManager_ReturnValue) == 0x0001F8, "Member 'BP_PlayerLevelStartSequenceTaskGetExpiredEquipmentInfos_C_NotifyDeletedMountsToLogAndMessage::CallFunc_GetSystemMessageManager_ReturnValue' has a wrong offset!");

}

