#pragma once

 

// Package: Config_KeyconfigItems

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Config_KeyconfigItems.Config_KeyconfigItems
// NumValues: 0x007E
enum class EConfig_KeyconfigItems : uint8
{
	NewEnumerator14                          = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator4                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator7                           = 7,
	NewEnumerator8                           = 8,
	NewEnumerator9                           = 9,
	NewEnumerator10                          = 10,
	NewEnumerator12                          = 11,
	NewEnumerator11                          = 12,
	NewEnumerator15                          = 13,
	NewEnumerator13                          = 14,
	NewEnumerator16                          = 15,
	NewEnumerator17                          = 16,
	NewEnumerator18                          = 17,
	NewEnumerator19                          = 18,
	NewEnumerator20                          = 19,
	NewEnumerator21                          = 20,
	NewEnumerator22                          = 21,
	NewEnumerator23                          = 22,
	NewEnumerator24                          = 23,
	NewEnumerator25                          = 24,
	NewEnumerator26                          = 25,
	NewEnumerator27                          = 26,
	NewEnumerator29                          = 27,
	NewEnumerator30                          = 28,
	NewEnumerator33                          = 29,
	NewEnumerator37                          = 30,
	NewEnumerator32                          = 31,
	NewEnumerator31                          = 32,
	NewEnumerator34                          = 33,
	NewEnumerator35                          = 34,
	NewEnumerator38                          = 35,
	NewEnumerator39                          = 36,
	NewEnumerator40                          = 37,
	NewEnumerator42                          = 38,
	NewEnumerator43                          = 39,
	NewEnumerator44                          = 40,
	NewEnumerator45                          = 41,
	NewEnumerator47                          = 42,
	NewEnumerator48                          = 43,
	NewEnumerator49                          = 44,
	NewEnumerator50                          = 45,
	NewEnumerator51                          = 46,
	NewEnumerator52                          = 47,
	NewEnumerator53                          = 48,
	NewEnumerator54                          = 49,
	NewEnumerator55                          = 50,
	NewEnumerator57                          = 51,
	NewEnumerator58                          = 52,
	NewEnumerator59                          = 53,
	NewEnumerator60                          = 54,
	NewEnumerator61                          = 55,
	NewEnumerator69                          = 56,
	NewEnumerator70                          = 57,
	NewEnumerator63                          = 58,
	NewEnumerator62                          = 59,
	NewEnumerator64                          = 60,
	NewEnumerator65                          = 61,
	NewEnumerator66                          = 62,
	NewEnumerator71                          = 63,
	NewEnumerator72                          = 64,
	NewEnumerator73                          = 65,
	NewEnumerator74                          = 66,
	NewEnumerator75                          = 67,
	NewEnumerator76                          = 68,
	NewEnumerator77                          = 69,
	NewEnumerator78                          = 70,
	NewEnumerator79                          = 71,
	NewEnumerator80                          = 72,
	NewEnumerator81                          = 73,
	NewEnumerator82                          = 74,
	NewEnumerator83                          = 75,
	NewEnumerator84                          = 76,
	NewEnumerator85                          = 77,
	NewEnumerator86                          = 78,
	NewEnumerator87                          = 79,
	NewEnumerator88                          = 80,
	NewEnumerator89                          = 81,
	NewEnumerator90                          = 82,
	NewEnumerator91                          = 83,
	NewEnumerator92                          = 84,
	NewEnumerator93                          = 85,
	NewEnumerator94                          = 86,
	NewEnumerator95                          = 87,
	NewEnumerator96                          = 88,
	NewEnumerator97                          = 89,
	NewEnumerator98                          = 90,
	NewEnumerator99                          = 91,
	NewEnumerator100                         = 92,
	NewEnumerator101                         = 93,
	NewEnumerator102                         = 94,
	NewEnumerator103                         = 95,
	NewEnumerator104                         = 96,
	NewEnumerator105                         = 97,
	NewEnumerator106                         = 98,
	NewEnumerator107                         = 99,
	NewEnumerator108                         = 100,
	NewEnumerator109                         = 101,
	NewEnumerator110                         = 102,
	NewEnumerator111                         = 103,
	NewEnumerator112                         = 104,
	NewEnumerator113                         = 105,
	NewEnumerator114                         = 106,
	NewEnumerator115                         = 107,
	NewEnumerator116                         = 108,
	NewEnumerator117                         = 109,
	NewEnumerator118                         = 110,
	NewEnumerator119                         = 111,
	NewEnumerator120                         = 112,
	NewEnumerator121                         = 113,
	NewEnumerator122                         = 114,
	NewEnumerator123                         = 115,
	NewEnumerator124                         = 116,
	NewEnumerator125                         = 117,
	NewEnumerator126                         = 118,
	NewEnumerator127                         = 119,
	NewEnumerator128                         = 120,
	NewEnumerator129                         = 121,
	NewEnumerator130                         = 122,
	NewEnumerator131                         = 123,
	NewEnumerator132                         = 124,
	Config_MAX                               = 125,
};

}

